### ISSUE TITLE
Specify and test rejection of invalid queries

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBItest#157]
- [ ] `dbSendQuery()`
- [ ] `dbSendStatement()`
- [ ] `dbSendQuery()` with parameters rejects only if parameters are passed, or after `dbBind()`
- [ ] `dbSendStatement()` with parameters rejects only if parameters are passed, or after `dbBind()`
- [ ] `dbGetQuery()` with parameters
- [ ] `dbExecute()` with parameters

@hadley @hannesmuehleisen @imanuelcostigan @jimhester: Do you think it's reasonable to postpone rejection of invalid parametrized queries to `dbBind()`, even if the backend might know earlier? This feels necessary for RPostgres, because it works much better if type information is submitted along with a parametrized query.

Reference: https://github.com/r-dbi/RPostgres/issues/139

**Comment by hannesmuehleisen** [comment]
Errors can happen in both phases, e.g. 

```
> res <- dbSendQuery(con, "prepare select blablubb")
Error in .local(conn, statement, ...) : 
  Unable to execute statement 'prepare select blablubb'.
Server says 'ParseException:SQLparser:SELECT: identifier 'blablubb' unknown'.
> res <- dbSendQuery(con, "prepare select cast (? as integer)")
> dbBind(res, list("blablubb"))
Error in .local(conn, statement, ...) : 
  Unable to execute statement 'EXECUTE 1('blablubb')'.
Server says 'ParseException:SQLparser:wrong type for argument 1 of function call: char, expected int '.
> 
```

I would assume that the query is correct (besides concrete parameter values) when `dbPrepare` returns successfully, that is, has been parsed and checked against schema. 
When `dbBind` fails, its only due to the parameter value being somehow the issue. 

I can however imagine backends that "fake" prepared query support in the client, and they would not know whether the query is correct after `dbPrepare`. So I would maybe suggest to allow dbPrepare to not throw an error in this case, but not forbid it either.

**Comment by krlmlr** [comment]
We can also suggest that users pass a 0-row data frame to `dbSendQuery()` if they want to prepare a query safely.

**Comment by imanuelcostigan** [comment]
@krlmlr given the excellent work done on `odbc` I doubt I will be investing a lot more time on RSQLServer.

**Comment by krlmlr** [comment]
Tests now require rejection of invalid queries only when all parameters are known or the new `immediate = TRUE` (8cc72df4c).
